#!/bin/bash

export XDG_CONFIG_HOME="$SNAP_USER_COMMON/.config"
export XDG_DATA_HOME="$SNAP_USER_COMMON/.local/share"
export XDG_CACHE_HOME="$SNAP_USER_COMMON/.cache"

mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_DATA_HOME"
mkdir -p "$XDG_CACHE_HOME"

if [ -d "$SNAP_USER_DATA/.config/Cemu" ]; then
    cp -r "$SNAP_USER_DATA/.config/Cemu" "$SNAP_USER_COMMON/.config/"
    rm -rf "$SNAP_USER_DATA/.config/Cemu"
fi

if [ -d "$SNAP_USER_DATA/.local/share/Cemu" ]; then
    cp -r "$SNAP_USER_DATA/.local/share/Cemu" "$SNAP_USER_COMMON/.local/share/"
    rm -rf "$SNAP_USER_DATA/.local/share/Cemu"
fi

exec "$@"
